import type { Recommendation, Challenge } from './types';

export const RECOMMENDATIONS_PRESET: Recommendation[] = [
  {
    id: 'rec_led_bulbs',
    title: 'Switch to LED Bulbs',
    description: 'Replace traditional incandescent lightbulbs with energy-efficient LEDs to cut lighting electricity by 80%.',
    category: 'energy',
    potentialSavings: 150,
    difficulty: 'easy',
    implemented: false,
  },
  {
    id: 'rec_lower_thermostat',
    title: 'Adjust Thermostat by 2°C',
    description: 'Lower your heater by 2°C in winter (or raise AC by 2°C in summer) to save natural gas and electricity.',
    category: 'energy',
    potentialSavings: 320,
    difficulty: 'easy',
    implemented: false,
  },
  {
    id: 'rec_cold_laundry',
    title: 'Wash Laundry in Cold Water',
    description: 'Heating water accounts for 90% of a washing machine\'s energy. Washing in cold water cuts emissions significantly.',
    category: 'energy',
    potentialSavings: 75,
    difficulty: 'easy',
    implemented: false,
  },
  {
    id: 'rec_solar_panels',
    title: 'Install Solar Panels',
    description: 'Generate your own clean electricity to offset coal/gas grid consumption completely and feed energy back.',
    category: 'energy',
    potentialSavings: 1800,
    difficulty: 'hard',
    implemented: false,
  },
  {
    id: 'rec_carpool',
    title: 'Carpool to Work or School',
    description: 'Share commutes with colleagues or classmates to divide transportation emissions and reduce road congestion.',
    category: 'transport',
    potentialSavings: 600,
    difficulty: 'medium',
    implemented: false,
  },
  {
    id: 'rec_active_travel',
    title: 'Walk or Bike for Trips < 3 km',
    description: 'Avoid starting your car for short trips. Walking or biking is emission-free and improves physical health.',
    category: 'transport',
    potentialSavings: 250,
    difficulty: 'easy',
    implemented: false,
  },
  {
    id: 'rec_electric_vehicle',
    title: 'Switch to a Hybrid or EV',
    description: 'Replace your fossil fuel vehicle with a hybrid or battery electric vehicle to drastically cut tailpipe emissions.',
    category: 'transport',
    potentialSavings: 2200,
    difficulty: 'hard',
    implemented: false,
  },
  {
    id: 'rec_staycation',
    title: 'Substitute 1 Flight with Trains',
    description: 'Substitute one regional flight with high-speed rail travel or choose a local staycation over flying.',
    category: 'transport',
    potentialSavings: 500,
    difficulty: 'medium',
    implemented: false,
  },
  {
    id: 'rec_meatless_weekdays',
    title: 'Go Meatless on Weekdays',
    description: 'Avoid red meat and poultry from Monday to Friday. Opt for vegetarian or vegan meals to cut dietary emissions.',
    category: 'food',
    potentialSavings: 650,
    difficulty: 'medium',
    implemented: false,
  },
  {
    id: 'rec_vegan_diet',
    title: 'Adopt a Vegan Diet',
    description: 'Eliminate all animal products to dramatically reduce agricultural land-use and greenhouse gas emissions.',
    category: 'food',
    potentialSavings: 1200,
    difficulty: 'hard',
    implemented: false,
  },
  {
    id: 'rec_compost',
    title: 'Compost Organic Waste',
    description: 'Compost your food scraps instead of sending them to landfills, where they rot anaerobically and release methane.',
    category: 'food',
    potentialSavings: 180,
    difficulty: 'easy',
    implemented: false,
  },
  {
    id: 'rec_local_food',
    title: 'Buy Local and Seasonal Foods',
    description: 'Purchase groceries from farmers markets or choose local brands to decrease the transportation footprint (food miles).',
    category: 'food',
    potentialSavings: 120,
    difficulty: 'easy',
    implemented: false,
  },
  {
    id: 'rec_zero_plastic',
    title: 'Eliminate Single-Use Plastics',
    description: 'Switch to reusable grocery bags, water bottles, and food containers to reduce waste hauling and plastic refining.',
    category: 'waste',
    potentialSavings: 80,
    difficulty: 'easy',
    implemented: false,
  },
  {
    id: 'rec_recycle_eighty',
    title: 'Recycle 80% of House Waste',
    description: 'Diligently sort paper, cardboard, metal cans, plastic bottles, and glass into municipal recycling streams.',
    category: 'waste',
    potentialSavings: 160,
    difficulty: 'easy',
    implemented: false,
  },
  {
    id: 'rec_buy_secondhand',
    title: 'Purchase Secondhand Goods',
    description: 'Buy clothes, furniture, and books pre-owned to extend product lifespans and avoid manufacturing emissions.',
    category: 'waste',
    potentialSavings: 240,
    difficulty: 'medium',
    implemented: false,
  },
];

export const CHALLENGES_PRESET: Challenge[] = [
  {
    id: 'ch_power_down',
    title: 'Power Down',
    description: 'Unplug all idle chargers, laptops, and appliance power strips today to stop "vampire power" draw.',
    category: 'energy',
    xp: 20,
    completed: false,
  },
  {
    id: 'ch_short_shower',
    title: '5-Minute Shower',
    description: 'Keep your shower under 5 minutes to save hot water and energy.',
    category: 'energy',
    xp: 25,
    completed: false,
  },
  {
    id: 'ch_active_travel',
    title: 'Active Commute',
    description: 'Leave the car key at home. Commute via walking, cycling, or public transit today.',
    category: 'transport',
    xp: 50,
    completed: false,
  },
  {
    id: 'ch_carpool',
    title: 'Ride Together',
    description: 'Carpool with a friend or colleague, or take public transit with someone else.',
    category: 'transport',
    xp: 30,
    completed: false,
  },
  {
    id: 'ch_green_plate',
    title: 'Plant-Powered Meals',
    description: 'Eat entirely plant-based meals today (no meat, dairy, eggs, or seafood).',
    category: 'food',
    xp: 40,
    completed: false,
  },
  {
    id: 'ch_no_food_waste',
    title: 'Clean Plate Club',
    description: 'Ensure zero edible food waste from your meals today. Save leftovers for tomorrow.',
    category: 'food',
    xp: 30,
    completed: false,
  },
  {
    id: 'ch_reusable_day',
    title: 'Zero Single-Use Plastic',
    description: 'Avoid all single-use packaging, straws, bags, and coffee cups for the entire day.',
    category: 'waste',
    xp: 35,
    completed: false,
  },
  {
    id: 'ch_recycle_check',
    title: 'Bin Master',
    description: 'Inspect your waste and correctly sort every single recyclable item into sorting bins.',
    category: 'waste',
    xp: 20,
    completed: false,
  },
];
